### ISSUE TITLE
An error occurred: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by mwiegers** [mrburrito/reinvent-sessions#15]
The error `An error occurred: Cannot read properties of undefined (reading 'split')` is thrown in the following scenarios:

1. Any "Personal time" entries made
2. Adding a meal time as favourite

The above due to these session not having a guaranteed location, which might as well be missing the | in it

**Comment by atkinsonm** [comment]
For me adding locations to personal time did not work, but deleting them did.

**Comment by mrburrito** [comment]
I think this is fixed with the changes I made for 2025. The split now handles a missing venue.

**Comment by acydgod** [comment]
Still getting the same error, I also have personal time scheduled with location populated

**Comment by mrburrito** [comment]
Debugging and updating. Should have it fixed in a few minutes.

**Comment by mrburrito** [comment]
@acydgod can you checkout the `personal-time` branch and re-run. It should work now. I'll merge the changes once you confirm!
